config/routes.rb
Fortune::Application.routes.draw do

  get "users/new"
  get "users/welcome"
  get "welcome/home"
  get "welcome/thank_you"
  get "welcome/register"

  resources :orders

  resources :cart_line_items

  resources :carts

   resources :line_items

  resources :rows

  resources :users

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "store/index"

  get "grid/index"

  get "grid/animals"

  get "grid/colours"

  get "grid/faces"

  get "grid/places"

  get "grid/plants"

  get "grid/shapes"

  get "grid/sky"

  get "grid/texture"

   get "grid/tshirt"

  get "grid/thanks"

  resources :shapes

  resources :sessions

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  root :to => "grid", :action => "index"
  root to: 'grid#index', as: 'grid'

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessible :email, :hashed_password, :password
  attr_accessor :password
  before_save :encrypt_password

  has_many :shapes
  has_many :orders


  validates :email,
            :uniqueness => true,
            :length => {:within => 5..50},
            :format => {:with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i}

  validates :password,
            :confirmation => true,
            :length => {:within => 4..20},
            :presence => true

  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password + "ruby_rocks" + self.salt)
  end
  protected
  def encrypt_password
    return if password.blank?
    salt = generate_salt
    self.hashed_password = encrypt(password + "ruby_rocks" + self.salt)
  end

  def encrypt(string)
    Digest::SHA1.hexdigest(string)
  end

  def generate_salt
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    salt = ""
    1.upto(10) { |i| salt << chars[rand(chars.size-1)] }
    self.salt = salt
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :is_admin?

  def index
    #@users = User.(:all)
    # below is depricated?

    #@users = User.find(:all)
    @users = User.all
    @cart = current_cart
    @row = current_row

  end

  def new
    @user = User.new
    @cart = current_cart
    @row = current_row
    @shapes = Shape.all
  end

   # welcome is from movies
  def welcome
    @shapes = Shape.all
    @cart = current_cart
    @row = current_row

    #@orders = Order.paginate page: params[:page], order: ' created_at desc',
        #per_page: 3

    @history = Order.paginate(:per_page => 3,
                              :page => params[:page],
                              :order => 'created_at DESC').where(user_id:current_user[:id])

    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end



  #def edit added from agile
  def edit
    @user = User.find(params[:id])
    @shapes = Shape.where(wanted: 'yes')
    @cart = current_cart
    @row = current_row
  end

  #def show added from agile
  def show
    @shapes = Shape.all
    @cart = current_cart
    @row = current_row

    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid user #{params[:id]}"
      redirect_to :controller => "grid", :action => 'index', notice: 'Invalid action'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def create
    @user = User.new(params[:user])
    @cart = current_cart
    @row = current_row
    @shapes = Shape.all

    if @user.save
      redirect_to login_path, :notice => 'User creation successful!'
    else
      render :action => 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Details were successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="fields">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="fields">
      <%= f.label :password %><br />
      <%= f.text_field :password %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<div id="main_padding">
  <h1>Editing User Details</h1>
  <%= render 'form' %>
  <% if current_user and current_user.admin %>
      <%= link_to 'Show', @user %> |
      <%= link_to 'Back', users_path %>
  <% else %>
      <%= link_to 'Back', :controller => "users", :action => "welcome", :notice => "Edited successfully" %>
  <% end %>
</div>

app/views/users/index.html.erb
<div id="main_padding">
  <% if current_user and current_user.admin %>
      <h1>Listing Users</h1>
      <table>
        <tr>
          <th>Email</th>
          <th>Admin</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        <% @users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
              <td><%= user.admin %></td>
              <td><%= link_to 'Show', user %></td>
              <td><%= link_to 'Edit', edit_user_path(user)%></td>
              <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
            </tr>
        <% end %>
  <% end %>
  </table>
  <br/>
  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div id="main_padding">
  <h2>Join So Random</h2>
  <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
          <div id="errorExplanation">
            <h2><%= pluralize(@user.errors.count, "error") %>
              prohibited this user from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </div>
      <div class="actions">
        <%= f.submit "Sign me up !"%>
      </div>
  <% end %>
  <%= link_to 'Back', shapes_path %>
</div>

app/views/users/show.html.erb
<div id="main_padding">
  <p id="notice"><%= notice %></p>
  <p>
    <b>email:</b>
    <%= @user.email %>
  </p>
  <p>
    <b>Password:</b>
    <%= @user.password %>
  </p>
  <% if current_user and current_user.admin %>
      <%= link_to 'Show', @user %> |
      <%= link_to 'Back', users_path %>
  <% else %>
      <%= link_to 'Back', :controller => "users", :action => "welcome", :notice => "Edited successfully" %>
  <% end %>
</div>

app/views/users/welcome.html.erb
  <div id="main_padding">
  <% if current_user and current_user.admin %>
      <h2>Welcome Administrator</h2>
      <b><%= current_user.email %></b>
      <%=  Time.now %><br/> <br/>
      <b> We have <%= @orders.to_a.length %> orders </b>

  <% else %>
      <h2>Welcome to So Random! </h2>
      <b><%= current_user.email %></b>
      <br/>
      <br/>
      would you like to edit your details?
      <%= link_to 'Edit', edit_user_path(current_user) %>
      <br/>
      <br/>
      <% if current_user and not current_user.admin %>

          <div>
            <fieldset>
              <legend><h2>Your Orders</h2></legend>
              <% @history.each do |order| %>
                  <b>Name:</b> <%= order.name %> <br/>
                  <b>Date of purchase:</b><%= order.created_at %> <br/>
                  <b>Pay type:</b><%= order.pay_type %> <br/>
                  <%= link_to 'Order Details', order %>  <br/>  <br/>
              <% end %>
              <% if current_user and not current_user.admin %>
                  <p><%= will_paginate @history %></p>
                  </fieldset>
              <% end %>
              </div>
      <% end %>

  <% end %>

</div>