config/routes.rb
Fortune::Application.routes.draw do

  get "users/new"
  get "users/welcome"
  get "welcome/home"
  get "welcome/thank_you"
  get "welcome/register"

  resources :orders

  resources :cart_line_items

  resources :carts

   resources :line_items

  resources :rows

  resources :users

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "store/index"

  get "grid/index"

  get "grid/animals"

  get "grid/colours"

  get "grid/faces"

  get "grid/places"

  get "grid/plants"

  get "grid/shapes"

  get "grid/sky"

  get "grid/texture"

   get "grid/tshirt"

  get "grid/thanks"

  resources :shapes

  resources :sessions

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  root :to => "grid", :action => "index"
  root to: 'grid#index', as: 'grid'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_line_items, dependent: :destroy

  def add_shape(shape_id)
    current_item = cart_line_items.find_by_shape_id(shape_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_line_items.build(shape_id: shape_id)
    end
    current_item
  end

  def total_price
    cart_line_items.to_a.sum { |item| item.total_price }
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
    @row = current_row
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json

  def show
    begin
      @cart = Cart.find(params[:id])
      @row = current_row
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to grid_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end
  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new
    @row = current_row

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])
    @row = current_row
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])
    @row = current_row

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    @row = current_row
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to :controller => "grid", :action => 'tshirt',
                                notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<h2>Your Cart</h2>
<table>
  <!-- START_HIGHLIGHT -->
  <%= render(cart.cart_line_items) %>
  <!-- END_HIGHLIGHT -->

  <tr class="total_line">
    <td colspan="2">Total</td>
    <!-- START_HIGHLIGHT -->
    <td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
    <!-- END_HIGHLIGHT -->
  </tr>

</table>

<!-- START_HIGHLIGHT -->
<%= button_to "Checkout", new_order_path, method: :get %>
<%= button_to 'Empty cart', cart, method: :delete,
              #END_HIGHLIGHT
              data: { confirm: 'Are you sure?' } %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div id="main">

  <div id="tshirt_sml">

    <div id="tshirt_sml_image" class="sml_image">

      <% @cart.cart_line_items.each do |item| %>


          <%= image_tag(item.shape.lrg_image_url) %></td>
    </div>

    <div id="tshirt_sml_text">
        <span class="tshirt_sml_text">
          <td><%= item.shape.text %>
          </span>
    </div>
      <% end %>
  </div>


  <div id="tshirt_control">


  <h2>Your Cart</h2>
  <table>
    <%= render(@cart.cart_line_items) %>


    <tr class="total_line">
      <td colspan="2">Total</td>
      <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
    </tr>

  </table>

    <%= button_to "Checkout", new_order_path, method: :get %>
  <%= button_to 'Empty cart', @cart, method: :delete,
                data: { confirm: 'Are you sure?' } %>

  </div>

</div>